version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/var/www/html:Z
      - ./data:/var/www/html/data:Z
    tmpfs:
      - /tmp
    ports:
      - '81:81'
    env_file: .env
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
    tmpfs:
      - /tmp
    ports:
      - '8080:8080'
    env_file: .env
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - '80:80'