version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/var/www/html:Z
    tmpfs:
      - /tmp
    ports:
      - '81:81'
    env_file: .env
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
    tmpfs:
      - /tmp
    ports:
      - '80:8080'
    env_file: .env