FROM trafex/alpine-nginx-php7

USER root

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN echo "user = nobody" >> /etc/php7/php-fpm.conf

CMD composer dumpautoload -o --no-interaction \
&& /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -u root
